CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" character varying(100) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PasswordHash" text NOT NULL,
        "Telefono" text,
        "Rol" character varying(20) NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE TABLE "Vehiculos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Marca" character varying(50) NOT NULL,
        "Modelo" character varying(50) NOT NULL,
        "Año" integer NOT NULL,
        "Precio" numeric(18,2) NOT NULL,
        "Descripcion" text,
        "Disponible" boolean NOT NULL,
        "TipoVehiculo" character varying(13) NOT NULL,
        "FechaPublicacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Vehiculos" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE TABLE "Notificaciones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Mensaje" text NOT NULL,
        "Tipo" character varying(20) NOT NULL,
        "FechaEnvio" timestamp with time zone NOT NULL,
        "Enviada" boolean NOT NULL,
        CONSTRAINT "PK_Notificaciones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notificaciones_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE TABLE "Turnos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UsuarioId" integer NOT NULL,
        "Fecha" timestamp with time zone NOT NULL,
        "Hora" interval NOT NULL,
        "TipoLavado" character varying(50) NOT NULL,
        "Estado" character varying(20) NOT NULL,
        "FechaFinalizacion" timestamp with time zone,
        "FechaCreacion" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Turnos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Turnos_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE TABLE "ImagenesVehiculos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VehiculoId" integer NOT NULL,
        "Url" text NOT NULL,
        "Key" text NOT NULL,
        "FechaSubida" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ImagenesVehiculos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ImagenesVehiculos_Vehiculos_VehiculoId" FOREIGN KEY ("VehiculoId") REFERENCES "Vehiculos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE INDEX "IX_ImagenesVehiculos_VehiculoId" ON "ImagenesVehiculos" ("VehiculoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE INDEX "IX_Notificaciones_UsuarioId" ON "Notificaciones" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE INDEX "IX_Turnos_UsuarioId" ON "Turnos" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Usuarios_Email" ON "Usuarios" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119043803_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251119043803_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Auto_Kilometraje" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Cilindrada" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Estado" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Kilometraje" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Puertas" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "TipoCombustible" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "TipoMoto" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    ALTER TABLE "Vehiculos" ADD "Transmision" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251119060840_AgregarPropiedadesConcesionaria') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251119060840_AgregarPropiedadesConcesionaria', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "Transmision" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "TipoMoto" TYPE character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "TipoCombustible" TYPE character varying(20);
    ALTER TABLE "Vehiculos" ALTER COLUMN "TipoCombustible" SET DEFAULT 'Nafta';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "Puertas" SET DEFAULT 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "Estado" SET DEFAULT 'Usado';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ALTER COLUMN "Cilindrada" SET DEFAULT 150;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ADD "EsDestacado" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    ALTER TABLE "Vehiculos" ADD "OrdenDestacado" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    CREATE INDEX "IX_Vehiculos_EsDestacado_OrdenDestacado" ON "Vehiculos" ("EsDestacado", "OrdenDestacado");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120051939_AgregarVehiculosDestacados') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251120051939_AgregarVehiculosDestacados', '8.0.11');
    END IF;
END $EF$;
COMMIT;

